# -*- coding: utf-8 -*-
"""Gojek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNaqc3Tf3Xa6sjcw-zCTdHfW_KWqvqag

# **LABEL DAN BALENCE DATA**
"""

import pandas as pd
import numpy as np

# 1. LOAD DATASET

filename = 'ulasan_com.gojek.app.csv'
try:
    df = pd.read_csv(filename)
    print("Dataset Gojek berhasil dimuat!")
except FileNotFoundError:
    print(f"File {filename} tidak ditemukan. Silakan upload dulu!")

df = df.dropna(subset=['Ulasan'])


# 2. HAPUS KELAS NETRAL & PELABELAN


df = df[df['Rating'] != 3].copy()

def labeling_sentiment(rating):
    if rating >= 4:
        return 'positive'
    else:
        return 'negative'

# kolom label
df['label'] = df['Rating'].apply(labeling_sentiment)

print("Distribusi Kelas Sebelum Balancing (Tanpa Netral):")
print(df['label'].value_counts())
print("-" * 40)


# 3. BALANCING DATA (UNDERSAMPLING)
# Cari jumlah data kelas terkecil (Negatif)

min_count = df['label'].value_counts().min()

df_pos = df[df['label'] == 'positive'].sample(n=min_count, random_state=42)
df_neg = df[df['label'] == 'negative'].sample(n=min_count, random_state=42)

# Gabung dataframe seimbang
df_balanced = pd.concat([df_pos, df_neg])
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\nDistribusi Kelas Setelah Balancing (Total: {len(df_balanced)} data):")
print(df_balanced['label'].value_counts())

# Buat Label Encoded (0: Negative, 1: Positive)
label_mapping = {'negative': 0, 'positive': 1}
df_balanced['label_encoded'] = df_balanced['label'].map(label_mapping)


# 4. SIMPAN DATASET BARU & VISUALISASI
# ==========================================
output_file = 'dataset_gojek_biner_balanced.csv'
df_balanced.to_csv(output_file, index=False)
print(f"\n Dataset 2 Kelas berhasil disimpan sebagai: '{output_file}'")

"""--------------------------------------------------------------------------

# **PREPROCESSING (CASEFOL, CLEAN, NORMAL, STOPW, STEMMER)**
"""

# Install library Sastrawi jika belum ada
!pip install Sastrawi
!pip install tqdm

import pandas as pd
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from tqdm import tqdm

# progress bar untuk pandas
tqdm.pandas()



# 1. LOAD DATASET

filename = 'dataset_gojek_biner_balanced.csv'
try:
    df = pd.read_csv(filename)
    print(f"Memproses {len(df)} data ulasan Gojek (Biner)...\n")
except FileNotFoundError:
    print(f"File {filename} tidak ditemukan. Pastikan sudah menjalankan kode sebelumnya!")

# Pastikan data teks berbentuk string
df['Ulasan'] = df['Ulasan'].astype(str)




# 2. FUNGSI PRE-PROCESSING


# A. Case Folding
def case_folding(text):
    return text.lower()

# B. Cleaning Text
def cleaning_text(text):
    text = re.sub(r'http\S+', '', text) # Hapus URL
    text = re.sub(r'(@\w+|#\w+)', '', text) # Hapus Mention dan Hashtag
    text = re.sub(r'[^a-zA-Z\s]', ' ', text) # Hapus angka dan tanda baca
    text = re.sub(r'\s+', ' ', text).strip() # Hapus spasi berlebih
    return text

# C. Normalization (Kamus Gaul Gojek)
norm_dict = {
    'apk': 'aplikasi', 'app': 'aplikasi', 'bgt': 'banget', 'bgtt': 'banget',
    'tdk': 'tidak', 'gak': 'tidak', 'gk': 'tidak', 'ga': 'tidak', 'enggak': 'tidak',
    'sy': 'saya', 'jg': 'juga', 'jd': 'jadi', 'krn': 'karena', 'kalo': 'kalau',
    'dgn': 'dengan', 'yg': 'yang', 'udah': 'sudah', 'udh': 'sudah', 'blm': 'belum',
    'driver': 'pengemudi', 'ojol': 'ojek online', 'gopay': 'saldo', 'min': 'admin',
    'nyasar': 'tersesat', 'lemot': 'lambat', 'lola': 'lambat', 'error': 'rusak',
    'update': 'perbarui', 'cpt': 'cepat', 'bgs': 'bagus', 'dr': 'dari', 'tp': 'tapi'
}

def normalization(text):
    words = text.split()
    normalized_words = [norm_dict.get(word, word) for word in words]
    return ' '.join(normalized_words)

# D. Stopword Removal
factory_stopword = StopWordRemoverFactory()
stopwords = factory_stopword.get_stop_words()
words_to_keep = ['tidak', 'kurang', 'bukan', 'jangan', 'belum']
custom_stopwords = [word for word in stopwords if word not in words_to_keep]

def remove_stopword(text):
    words = text.split()
    filtered_words = [word for word in words if word not in custom_stopwords]
    return ' '.join(filtered_words)

# E. Stemming
factory_stemmer = StemmerFactory()
stemmer = factory_stemmer.create_stemmer()

def stemming(text):
    return stemmer.stem(text)



# 3. EKSEKUSI PRE-PROCESSING

print("🔄 1/5 Memproses Case Folding...")
df['clean_text'] = df['Ulasan'].apply(case_folding)

print("🔄 2/5 Memproses Cleaning Text...")
df['clean_text'] = df['clean_text'].apply(cleaning_text)

print("🔄 3/5 Memproses Normalization...")
df['clean_text'] = df['clean_text'].apply(normalization)

print("🔄 4/5 Memproses Stopword Removal...")
df['clean_text'] = df['clean_text'].apply(remove_stopword)

print("🔄 5/5 Memproses Stemming (Estimasi 45-60 Menit. Silakan ditinggal ngopi!)...")
# progress_apply untuk melihat loading bar
df['clean_text'] = df['clean_text'].progress_apply(stemming)

# Hapus baris kosong akibat proses cleaning
df = df[df['clean_text'].str.strip() != '']
df = df.dropna(subset=['clean_text'])

# 4. SIMPAN HASIL BERSIH

output_file = 'dataset_gojek_biner_bersih.csv'
df.to_csv(output_file, index=False)
print(f"\n Pre-processing Selesai! Data bersih disimpan sebagai: '{output_file}'")

# Tampilkan sampel
print("\n SAMPEL DATA BERSIH (BINER):")
print(df[['Ulasan', 'clean_text', 'label']].sample(5, random_state=42))

"""--------------------------------------------------------------------------

## **Training 5 Konfigurasi**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import time

# 1. LOAD DATA
df = pd.read_csv('dataset_gojek_biner_bersih.csv')
X = df['clean_text'].astype(str).values
y = df['label_encoded'].values

# Tokenization
max_words, max_len = 5000, 50
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(X)
X_pad = pad_sequences(tokenizer.texts_to_sequences(X), maxlen=max_len)
X_train, X_test, y_train, y_test = train_test_split(X_pad, y, test_size=0.2, random_state=42)

# 2. KONFIGURASI 5 SKENARIO
skenarios = [
    {"epoch": 10, "dropout": 0.2, "unit": 64, "batch": 32, "rdropout": 0.2},
    {"epoch": 20, "dropout": 0.2, "unit": 64, "batch": 32, "rdropout": 0.2},
    {"epoch": 30, "dropout": 0.2, "unit": 64, "batch": 32, "rdropout": 0.2},
    {"epoch": 50, "dropout": 0.5, "unit": 64, "batch": 32, "rdropout": 0.2},
    {"epoch": 20, "dropout": 0.2, "unit": 128, "batch": 32, "rdropout": 0.2},
]

all_results = []

# 3. PROSES TRAINING OTOMATIS
for i, config in enumerate(skenarios):
    print(f"\n{'='*40}")
    print(f"RUNNING SKENARIO {i+1} / 5")
    print(f"Konfigurasi: {config}")
    print(f"{'='*40}")

    model = Sequential([
        Embedding(max_words, 128, input_length=max_len),
        LSTM(config['unit'], dropout=config['dropout'], recurrent_dropout=config['rdropout']),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    # Training
    history = model.fit(X_train, y_train, epochs=config['epoch'], batch_size=config['batch'],
                        validation_data=(X_test, y_test), verbose=1)

    # Prediksi & Evaluasi
    y_pred = (model.predict(X_test) > 0.5).astype("int32")
    report = classification_report(y_test, y_pred, output_dict=True)
    acc = accuracy_score(y_test, y_pred)

    # Simpan hasil untuk grafik akhir
    all_results.append({
        "skenario": i+1,
        "acc": acc,
        "f1": report['macro avg']['f1-score'],
        "prec": report['weighted avg']['precision'],
        "rec": report['weighted avg']['recall'],
        "config": f"S{i+1}"
    })

    # Output Visual
    fig, ax = plt.subplots(1, 3, figsize=(20, 5))

    # Plot Accuracy (Warna Biru & Orange Standar)
    ax[0].plot(history.history['accuracy'], label='Train Acc')
    ax[0].plot(history.history['val_accuracy'], label='Val Acc')
    ax[0].set_title(f'S{i+1}: Model Accuracy')
    ax[0].legend()

    # Plot Loss
    ax[1].plot(history.history['loss'], label='Train Loss')
    ax[1].plot(history.history['val_loss'], label='Val Loss')
    ax[1].set_title(f'S{i+1}: Model Loss')
    ax[1].legend()

    # Plot Confusion Matrix
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues', ax=ax[2])
    ax[2].set_title(f'S{i+1}: Confusion Matrix')


    plt.tight_layout()
    plt.show()

    # TABEL DETAIL
    print(f"\n HASIL EVALUASI SKENARIO {i+1}")
    print("-" * 65)
    print(f"{'Kelas':<15} | {'Precision':<10} | {'Recall':<10} | {'F1-Score':<10}")
    print("-" * 65)
    for l, n in [('0', 'Negative'), ('1', 'Positive')]:
        print(f"{n:<15} | {report[l]['precision']:.4f}     | {report[l]['recall']:.4f}   | {report[l]['f1-score']:.4f}")
    print("-" * 65)
    print(f"{'Macro Avg':<15} | {report['macro avg']['precision']:.4f}     | {report['macro avg']['recall']:.4f}   | {report['macro avg']['f1-score']:.4f}")
    print(f"{'Weighted Avg':<15} | {report['weighted avg']['precision']:.4f}     | {report['weighted avg']['recall']:.4f}   | {report['weighted avg']['f1-score']:.4f}")
    print("-" * 65)
    print(f"TOTAL ACCURACY : {acc:.4f}\n")

# 4. GRAFIK EVALUASI KOMPARASI AKHIR
print("\n Menghasilkan Grafik Perbandingan Semua Skenario...")
summary_df = pd.DataFrame(all_results)

plt.figure(figsize=(12, 6))
plt.plot(summary_df['config'], summary_df['acc'], marker='o', label='Accuracy', linewidth=2)
plt.plot(summary_df['config'], summary_df['f1'], marker='s', label='F1-Score (Macro)', linestyle='--')
plt.plot(summary_df['config'], summary_df['prec'], marker='^', label='Precision (Weighted)', linestyle=':')



plt.title('Perbandingan Performa Model antar Skenario', fontsize=14)
plt.ylabel('Score')
plt.xlabel('Skenario')
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# 1. Load data langsung dari file CSV
data_wc = pd.read_csv('dataset_gojek_biner_bersih.csv')

# 2. Pisahkan teks berdasarkan label (1=Positive, 0=Negative)
# Gunakan kolom 'clean_text' karena sudah diproses
pos_txt = " ".join(data_wc[data_wc['label_encoded'] == 1]['clean_text'].astype(str))
neg_txt = " ".join(data_wc[data_wc['label_encoded'] == 0]['clean_text'].astype(str))

# 3. Fungsi untuk membuat Word Cloud
def tampilkan_wordcloud(teks, judul, warna):
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white',
        max_words=100,
        colormap=warna,
        collocations=False
    ).generate(teks)
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title(judul, fontsize=18, pad=15)
    plt.show()

# 4. Eksekusi
print("🔍 Sedang memproses Word Cloud dari dataset...")
tampilkan_wordcloud(pos_txt, 'Wordcloud Sentimen POSITIF', 'Blues')
tampilkan_wordcloud(neg_txt, 'Wordcloud Sentimen NEGATIF', 'Reds')